apiVersion: v1
kind: Secret
metadata:
  namespace: wow
  name: wotlk-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "mangos"
  MYSQL_USER: "mangos"
  MYSQL_PASSWORD: "mangos"
  MYSQL_HOST: "wotlk-mysql-svc"
  LOGIN_DATABASE_INFO: "wotlk-mysql-svc;3306;mangos;mangos;wotlkrealmd"
  WORLD_DATABASE_INFO: "wotlk-mysql-svc;3306;mangos;mangos;wotlkmangos"
  CHARACTER_DATABASE_INFO: "wotlk-mysql-svc;3306;mangos;mangos;wotlkcharacters"
  LOGS_DATABASE_INFO: "wotlk-mysql-svc;3306;mangos;mangos;wotlklogs"
  TZ: "Asia/Shanghai"