apiVersion: v1
kind: Service
metadata:
  namespace: wow
  name: wotlk-realmd-svc
spec:
  ports:
    - port: 3724
      targetPort: 3724
  selector:
    app: wotlk-realmd
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wow
  name: wotlk-realmd
spec:
  selector:
    matchLabels:
      app: wotlk-realmd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wotlk-realmd
    spec:
      initContainers:
        - name: check-mysql
          image: mysql
          command:
            - sh
            - -c
            - |            #!/bin/bash
              until mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e ''; do
                >&2 echo "MySQL is unavailable - sleeping-30s"
                sleep 30
              done
          envFrom:
            - secretRef:
                name: wotlk-secrets
      containers:
        - image: king607267/cmangos-wotlk-realmd #x86 king607267/cmangos-wotlk-realmd
          name: wotlk-realmd
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: 3724
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 3724
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "5Mi"
            limits:
              cpu: "200m"
              memory: "20Mi"
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: wotlk-secrets
                  key: TZ
            - name: LOGIN_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: wotlk-secrets
                  key: LOGIN_DATABASE_INFO
          ports:
            - containerPort: 3724
              name: wotlk-realmd
---
apiVersion: v1
kind: Service
metadata:
  namespace: wow
  name: wotlk-server-svc
spec:
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: wotlk-server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  namespace: wow
  name: wotlk-server-soap
spec:
  ports:
    - port: 7878
      targetPort: 7878
  selector:
    app: wotlk-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wow
  name: wotlk-server
spec:
  selector:
    matchLabels:
      app: wotlk-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wotlk-server
    spec:
      initContainers:
        - name: check-mysql
          image: mysql
          command:
            - sh
            - -c
            - |            #!/bin/bash
              until mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e ''; do
                >&2 echo "MySQL is unavailable - sleeping-30s"
                sleep 30
              done
          envFrom:
            - secretRef:
                name: wotlk-secrets
      terminationGracePeriodSeconds: 120
      containers:
        - image: king607267/cmangos-wotlk-server #x86 king607267/cmangos-wotlk-server
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: 8085
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 8085
            periodSeconds: 30
          name: wotlk-server
          lifecycle:
            preStop:
              exec:
                command: [ ".server restart", "60" ]
          resources:
            requests:
              cpu: "100m"
              memory: "650Mi"
            limits:
              cpu: "1"
              memory: "1.5Gi"
          stdin: true
          tty: true
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: wotlk-secrets
                  key: TZ
            - name: LOGIN_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: wotlk-secrets
                  key: LOGIN_DATABASE_INFO
            - name: WORLD_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: wotlk-secrets
                  key: WORLD_DATABASE_INFO
            - name: CHARACTER_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: wotlk-secrets
                  key: CHARACTER_DATABASE_INFO
            - name: LOGS_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: wotlk-secrets
                  key: LOGS_DATABASE_INFO
          ports:
            - containerPort: 8085
              name: wotlk-server
            - containerPort: 7878
              name: ser-cla-soap
          volumeMounts:
            - name: wow-nfs
              subPath: wotlk/map
              mountPath: /etc/mangos/data
            - name: wow-nfs
              subPath: wotlk/conf
              mountPath: /etc/mangos/conf
      volumes:
        - nfs:
            path: /mnt/nfs/WoW
            server: nfs.server
          name: wow-nfs