cmangos:
  type: classic
  namespaceOverride: wow

realmd:
  enabled: true
  tagName: latest
  nodeSelector: ""
  service:
    port: 3724
    type: LoadBalancer
  resources:
    requests:
      cpu: 0.1
      memory: 5Mi
    limits:
      cpu: 0.2
      memory: 20Mi

server:
  enabled: true
  tagName: latest
  nodeSelector: ""
  service:
    port: 8085
    soa:
      port: 7878
    type: LoadBalancer
  resources:
    requests:
      cpu: 0.1
      memory: 600Mi
    limits:
      cpu: 0.8
      memory: 1544Mi

mysql:
  enabled: true
  changeIpJob:
    enabled: true
  dbBackupJob:
    enabled: true
  tagName: latest
  customSqlURL: #Execute after the database is ready for example import accounts
  externalURL: ""
  realm:
    ip: 127.0.0.1
    name: MaNGOS
    port: 8085
  nodeSelector: ""
  service:
    type: LoadBalancer
  user: mangos
  password: mangos
  rootPassword: mangos
  port: 3306
  tz: Asia/Shanghai
  i18n: Chinese #Chinese，French，German，Italian，Korean，Russian，Spanish，Spanish_South_American，Taiwanese
  resources:
    requests:
      cpu: 0.2
      memory: 300Mi
    limits:
      cpu: 1
      memory: 750Mi

image:
  pullPolicy: IfNotPresent
  restartPolicy: Always

# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
# │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
job:
  changeIp:
    schedule: "*/30 * * * *"
    ttlSecondsAfterFinished: 900 #15min
  dbBackup:
    schedule: "0 18 * * *"#https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#writing-a-cronjob-spec
    ttlSecondsAfterFinished: 14400 #4h

registration:
  enabled: true
  tagName: latest
  nodeSelector: ""
  service:
    type: LoadBalancer
  tls:
    enabled: false
    port: 443
    url:
  http:
    port: 80
  expansion: 0 #0 classic,1 tbc,2 wotlk
  resources:
    requests:
      cpu: 0.1
      memory: 50Mi
    limits:
      cpu: 0.2
      memory: 100Mi

gateway:
  ip: 127.0.0.1
  realmd:
    port: 3724
  server:
    port: 8085
  registration:
    domain: wow.example.com
    port: 80
    tls:
      enabled: false
      port: 443

nfs:
  server: 127.0.0.1
  path: /mnt/nfs/WoW