cmangos:
  type: classic

realmd:
  nodeSelector: "kubernetes.io/arch: arm64"
  service:
    port: 3724
    type: LoadBalancer
  resources:
    requests:
      cpu: 0.1
      memory: 5Mi
    limits:
      cpu: 0.2
      memory: 20Mi

server:
  nodeSelector: "kubernetes.io/arch: arm64"
  service:
    port: 8085
    soa:
      port: 7878
    type: LoadBalancer
  resources:
    requests:
      cpu: 0.1
      memory: 600Mi
    limits:
      cpu: 0.8
      memory: 1024Mi

mysql:
  realm:
    ip: 127.0.0.1
    name: MaNGOS
    port: 8060
  nodeSelector: "disk: h-p_ssd"
  service:
    type: LoadBalancer
  user: mangos
  password: mangos
  root_password: mangos
  port: 3306
  tz: Asia/Shanghai
  i18n: Chinese #Chinese，French，German，Italian，Korean，Russian，Spanish，Spanish_South_American，Taiwanese
  resources:
    requests:
      cpu: 0.2
      memory: 300Mi
    limits:
      cpu: 1
      memory: 750Mi

image:
  pullPolicy: Always
  restartPolicy: Always

# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
# │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
job:
  changeIp:
    schedule: "*/30 * * * *"
    ttlSecondsAfterFinished: 900 #15min
  dbBackup:
    schedule: "0 18 * * *"#https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#writing-a-cronjob-spec
    ttlSecondsAfterFinished: 14400 #4h

registration:
  nodeSelector: "kubernetes.io/arch: arm64"
  ssl:
    port: 443
  http:
    port: 80
  expansion: 0 #0 classic,1 tbc,2 wotlk
  resources:
    requests:
      cpu: 0.1
      memory: 50Mi
    limits:
      cpu: 0.2
      memory: 100Mi

nfs:
  server: 127.0.0.1
  path: /mnt/user/share/WoW/docker