FROM mysql:5.7
MAINTAINER wangjueming <king607267@gmail.com>
EXPOSE 3306

ARG CMANGOS_DATABASE_VERSION=master

ENV CMANGOS_SERVER_VERSION=classic

RUN apt-get update && \
    apt-get install git wget -y && \
    git clone https://github.com/cmangos/mangos-classic.git -b ${CMANGOS_DATABASE_VERSION} --recursive --depth=1 && \
    git clone https://github.com/cmangos/classic-db.git -b ${CMANGOS_DATABASE_VERSION} --recursive --depth=1 && \
    wget --no-check-certificate https://raw.githubusercontent.com/king607267/cmangos-docker/master/launch_mysql.sh && \
    cd ./mangos-classic && \
    rm -rf `ls |egrep -v '(sql)'` && \
    cd .. && \
    chmod -R a+x,a+w,a+r ./classic-db && \
    chmod a+x launch_mysql.sh && \
    apt-get remove --purge --force-yes -y git wget && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["./launch_mysql.sh"]
CMD ["mysqld"]
