apiVersion: apps/v1
kind: PersistentVolume
metadata:
  namespace: classic
  name: classic-mysql-pv
spec:
  storageClassName: ""
  claimRef:
    name: classic-mysql-pvc
    namespace: classic
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/mysql/classic/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: classic
  name: classic-mysql-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: classic
  name: classic-maps-pv
spec:
  capacity:
    storage: 2Gi
  storageClassName: ""
  claimRef:
    name: classic-maps-pvc
    namespace: classic
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs/WoW/classic/map
    server: $nfs.server
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: classic
  name: classic-maps-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi # 2Gi 3Gi 4.5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: classic
  name: classic-conf-pv
spec:
  capacity:
    storage: 20Mi
  storageClassName: ""
  claimRef:
    name: classic-conf-pvc
    namespace: classic
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs/WoW/classic/conf
    server: $nfs.server
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: classic
  name: classic-conf-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi