#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  namespace: wow
#  name: classic-mysql-pv
#spec:
#  storageClassName: ""
#  claimRef:
#    name: classic-mysql-pvc
#    namespace: wow
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: "/data/mysql"
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  namespace: wow
#  name: classic-mysql-pv
#spec:
#  storageClassName: ""
#  claimRef:
#    name: classic-mysql-pvc
#    namespace: wow
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  nfs:
#    path: /mnt/nfs/WoW/classic/mysql
#    server: nfs.server
#    readOnly: false
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  namespace: wow
#  name: classic-mysql-pvc
#spec:
#  storageClassName: ""
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi
#---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wow-maps-pv
spec:
  capacity:
    storage: 2Gi
  storageClassName: ""
  claimRef:
    name: wow-maps-pvc
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs/WoW
    server: nfs.server
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wow
  name: wow-maps-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi # 2Gi 3Gi 4.5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wow
  name: wow-conf-pv
spec:
  capacity:
    storage: 20Mi
  storageClassName: ""
  claimRef:
    name: wow-conf-pvc
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs/WoW
    server: nfs.server
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wow
  name: wow-conf-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi