#default classic
ARG CMANGOS_CORE=classic

FROM ubuntu:22.04 AS build-step
ARG CMANGOS_CORE=classic
ARG THREAD_COUNT="-j4"
ENV TZ=Asia/Shanghai

COPY mangos-${CMANGOS_CORE} mangos-${CMANGOS_CORE}
RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install tzdata build-essential gcc g++ automake git-core autoconf make patch libmysql++-dev libtool libssl-dev grep binutils zlib1g-dev libbz2-dev cmake libboost-all-dev -y && \
    apt install g++-12 -y && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12 --slave /usr/bin/g++ g++ /usr/bin/g++-12 && \
    mkdir build && cd build
RUN cmake ../mangos-${CMANGOS_CORE} -DPCH=1 -DDEBUG=0 -DBUILD_EXTRACTORS=ON -DCMAKE_INSTALL_PREFIX=\../mangos-${CMANGOS_CORE}/run && \
    make ${THREAD_COUNT} && \
    make install ${THREAD_COUNT}
RUN cd /mangos-${CMANGOS_CORE}/run/bin && tar -czf mangosd.tar.gz mangosd && \
    cd /mangos-${CMANGOS_CORE}/sql/updates && tar -czf updates-sql.tar.gz characters/ logs/ mangos/ realmd/

#Runtime image realmd
FROM ubuntu:22.04 AS realmd

EXPOSE 3724
ARG CMANGOS_CORE
ENV CMANGOS_CORE=${CMANGOS_CORE}
ENV TARGET=realmd
ENV LOGIN_DATABASE_INFO=127.0.0.1;3306;root;mangos;${CMANGOS_CORE}realmd
ENV TZ=Asia/Shanghai

WORKDIR /etc/mangos/
COPY --from=build-step /mangos-${CMANGOS_CORE}/run/bin/realmd ./bin/realmd
COPY --from=build-step /mangos-${CMANGOS_CORE}/sql/updates/updates-sql.tar.gz ./updates-sql.tar.gz
COPY --from=build-step /mangos-${CMANGOS_CORE}/run/etc ./conf
COPY run-realmd.sh ./run-realmd.sh
COPY update-db-ver.sh ./update-db-ver.sh
COPY kill-server.sh ./kill-server.sh

RUN apt-get -y update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata libmysqlclient-dev mysql-client openssl && rm -rf /var/lib/apt/lists/*
RUN useradd -ms /bin/bash realm && \
    mv conf/realmd.conf.dist conf/realmd.conf && \
    chmod u+x run-realmd.sh && \
    chmod u+x update-db-ver.sh && \
    chmod u+x kill-server.sh && \
    chown -R realm:realm .

USER realm
CMD ["./run-realmd.sh"]

#Runtime image mangosd
FROM ubuntu:22.04 AS mangosd

EXPOSE 8085
ARG CMANGOS_CORE
ENV CMANGOS_CORE=${CMANGOS_CORE}
ENV TARGET=mangosd
ENV LOGIN_DATABASE_INFO=127.0.0.1;3306;root;mangos;${CMANGOS_CORE}realmd
ENV WORLD_DATABASE_INFO=127.0.0.1;3306;root;mangos;${CMANGOS_CORE}mangos
ENV CHARACTER_DATABASE_INFO=127.0.0.1;3306;root;mangos;${CMANGOS_CORE}characters
ENV LOGS_DATABASE_INFO=127.0.0.1;3306;root;mangos;${CMANGOS_CORE}logs
ENV TZ=Asia/Shanghai

WORKDIR /etc/mangos/
COPY --from=build-step /mangos-${CMANGOS_CORE}/run/bin/mangosd.tar.gz ./bin/mangosd.tar.gz
COPY --from=build-step /mangos-${CMANGOS_CORE}/sql/updates/updates-sql.tar.gz ./updates-sql.tar.gz
COPY --from=build-step /mangos-${CMANGOS_CORE}/run/etc ./conf
COPY --from=build-step /mangos-${CMANGOS_CORE}/src/game/AuctionHouseBot/ahbot.conf.dist.in ./conf/ahbot.conf
COPY run-mangos.sh ./run-mangos.sh
COPY update-db-ver.sh ./update-db-ver.sh
COPY kill-server.sh ./kill-server.sh

RUN apt-get -y update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata libmysqlclient-dev mysql-client openssl p7zip-full && rm -rf /var/lib/apt/lists/*
RUN useradd -ms /bin/bash mangos && \
    mv conf/mangosd.conf.dist conf/mangosd.conf && \
    sed -i 's/^DataDir = "."/DataDir = "\/etc\/mangos\/data"/' conf/mangosd.conf && \
    chmod u+x run-mangos.sh && \
    chmod u+x update-db-ver.sh && \
    chmod u+x kill-server.sh && \
    chown -R mangos:mangos .

COPY --chown=mangos:mangos --chmod=644 ${CMANGOS_CORE}_maps.7z ./${CMANGOS_CORE}_maps.7z

USER mangos
CMD ["./run-mangos.sh"]

#Runtime image extractors
FROM ubuntu:22.04 AS extractors

ARG CMANGOS_CORE
ENV CMANGOS_CORE=${CMANGOS_CORE}
ENV TARGET=extractors
ENV TZ=Asia/Shanghai

WORKDIR /etc/mangos/

COPY --from=build-step /mangos-${CMANGOS_CORE}/run/bin/tools ./tools
COPY run-cp-extractors.sh ./run-cp-extractors.sh

RUN chmod u+x run-cp-extractors.sh

CMD ["./run-cp-extractors.sh"]

