FROM mysql:5.7
MAINTAINER wangjueming <king607267@gmail.com>
EXPOSE 3306

#default master
ARG CMANGOS_DATABASE_BRANCH=master
#default master
ARG CMANGOS_SERVER_BRANCH=master
#default classic
ARG CMANGOS_CORE=classic

ENV CMANGOS_CORE=${CMANGOS_CORE}

ENV REALM_IP=127.0.0.1
ENV REALM_PORT=8085
ENV REALM_NAME=MaNGOS

#COPY launch_mysql.sh ./

RUN apt-get update -qq && \
    apt-get install git wget -y && \
    git clone https://github.com/cmangos/mangos-${CMANGOS_CORE}.git -b ${CMANGOS_SERVER_BRANCH} --recursive --depth=1 && \
    git clone https://github.com/cmangos/${CMANGOS_CORE}-db.git -b ${CMANGOS_DATABASE_BRANCH} --recursive --depth=1 && \
    wget --no-check-certificate https://raw.githubusercontent.com/king607267/cmangos-wrapper/master/docker/launch_mysql.sh && \
    cd ./mangos-${CMANGOS_CORE} && \
    rm -rf `ls |egrep -v '(sql)'` && \
    rm -rf .git && \
    cd ../${CMANGOS_CORE}-db && \
    rm -rf `ls |egrep -v '(ACID|Full_DB|Updates|utilities|InstallFullDB.sh)'` && \
    rm -rf .git && \
    cd .. && \
    chmod -R a+x,a+w,a+r ./${CMANGOS_CORE}-db && \
    chmod a+x launch_mysql.sh && \
    apt-get remove --purge --force-yes -y git wget && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["./launch_mysql.sh"]
CMD ["mysqld"]
