apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1.5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/docker/" #TODO
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-60-svc
spec:
  ports:
    - port: 3360
      targetPort: 3306
  selector:
    app: mysql-60
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-60
spec:
  selector:
    matchLabels:
      app: mysql-60
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-60
    spec:
      containers:
        - image: king607267/cmangos-classic-db
          name: mysql-60
          env:
            # TODO Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: mangos
            - name: MYSQL_PASSWORD
              value: mangos
            - name: MYSQL_USER
              value: mangos
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
              subPath: mysql/60
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: realmd-60-svc
spec:
  ports:
    - port: 3724
      targetPort: 3724
      nodePort: 30724
  selector:
    app: realmd-60
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realmd-60
spec:
  selector:
    matchLabels:
      app: realmd-60
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: realmd-60
    spec:
      containers:
        - image: king607267/cmangos-classic-realmd
          name: realmd60
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: LOGIN_DATABASE_INFO
              value: mysql-60-svc;3306;mangos;mangos;classicrealmd
          ports:
            - containerPort: 3724
              name: realmd-60
---
apiVersion: v1
kind: Service
metadata:
  name: server-60-svc
spec:
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
  selector:
    app: server-60
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-60
spec:
  selector:
    matchLabels:
      app: server-60
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server-60
    spec:
      containers:
        - image: king607267/cmangos-classic-server
          name: server60
          stdin: true
          tty: true
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: LOGIN_DATABASE_INFO
              value: mysql-60-svc;3306;mangos;mangos;classicrealmd
            - name: WORLD_DATABASE_INFO
              value: mysql-60-svc;3306;mangos;mangos;classicmangos
            - name: CHARACTER_DATABASE_INFO
              value: mysql-60-svc;3306;mangos;mangos;classiccharacters
            - name: LOGS_DATABASE_INFO
              value: mysql-60-svc;3306;mangos;mangos;classiclogs
          ports:
            - containerPort: 8085
              name: server-60
          volumeMounts:
          - name: mangos-maps
            mountPath: /etc/mangos/maps
          - name: mangos-vmaps
            mountPath: /etc/mangos/vmaps
          - name: mangos-mmaps
            mountPath: /etc/mangos/mmaps
          - name: mangos-dbc
            mountPath: /etc/mangos/dbc
      volumes:
        - name: mangos-maps
          hostPath:
            path: /home/docker/maps/60/maps
        - name: mangos-vmaps`
          hostPath:
            path: /home/docker/maps/60/vmaps
        - name: mangos-mmaps
          hostPath:
            path: /home/docker/maps/60/mmaps
        - name: mangos-dbc
          hostPath:
            path: /home/docker/maps/60/dbc