FROM mysql:5.7
MAINTAINER wangjueming <king607267@gmail.com>
EXPOSE 3306

ARG CMANGOS_DATABASE_VERSION=master

ENV CMANGOS_SERVER_VERSION=tbc

RUN apt-get update && \
    apt-get install git wget -y && \
    git clone https://github.com/cmangos/mangos-tbc.git -b ${CMANGOS_DATABASE_VERSION} --recursive --depth=1 && \
    git clone https://github.com/cmangos/tbc-db.git -b ${CMANGOS_DATABASE_VERSION} --recursive --depth=1 && \
    wget --no-check-certificate https://raw.githubusercontent.com/king607267/cmangos-docker/master/launch_mysql.sh && \
    cd ./mangos-tbc && \
    rm -rf `ls |egrep -v '(sql)'` && \
    rm -rf .git && \
    cd ../tbc-db && \
    rm -rf `ls |egrep -v '(ACID|Full_DB|Updates|utilities|InstallFullDB.sh)'` && \
    rm -rf .git && \
    cd .. && \
    chmod -R a+x,a+w,a+r ./tbc-db && \
    chmod a+x launch_mysql.sh && \
    apt-get remove --purge --force-yes -y git wget && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["./launch_mysql.sh"]
CMD ["mysqld"]
