apiVersion: v1
kind: Secret
metadata:
  namespace: wow
  name: tbc-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "mangos"
  MYSQL_USER: "mangos"
  MYSQL_PASSWORD: "mangos"
  MYSQL_HOST: "tbc-mysql-svc"
  LOGIN_DATABASE_INFO: "tbc-mysql-svc;3306;mangos;mangos;tbcrealmd"
  WORLD_DATABASE_INFO: "tbc-mysql-svc;3306;mangos;mangos;tbcmangos"
  CHARACTER_DATABASE_INFO: "tbc-mysql-svc;3306;mangos;mangos;tbccharacters"
  LOGS_DATABASE_INFO: "tbc-mysql-svc;3306;mangos;mangos;tbclogs"
  TZ: "Asia/Shanghai"