apiVersion: v1
kind: Service
metadata:
  namespace: wow
  name: tbc-realmd-svc
spec:
  ports:
    - port: 3724
      targetPort: 3724
  selector:
    app: tbc-realmd
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wow
  name: tbc-realmd
spec:
  selector:
    matchLabels:
      app: tbc-realmd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tbc-realmd
    spec:
      initContainers:
        - name: check-mysql
          image: mysql
          command:
            - sh
            - -c
            - |            #!/bin/bash
              until mysql --connect-timeout=5 -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e ''; do
                >&2 echo "MySQL is unavailable - sleeping-30s"
                sleep 30
              done
          envFrom:
            - secretRef:
                name: tbc-secrets
      containers:
        - image: king607267/cmangos-tbc-realmd
          name: tbc-realmd
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: 3724
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 3724
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "5Mi"
            limits:
              cpu: "200m"
              memory: "20Mi"
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: tbc-secrets
                  key: TZ
            - name: LOGIN_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: tbc-secrets
                  key: LOGIN_DATABASE_INFO
          ports:
            - containerPort: 3724
              name: tbc-realmd
---
apiVersion: v1
kind: Service
metadata:
  namespace: wow
  name: tbc-server-svc
spec:
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: tbc-server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  namespace: wow
  name: tbc-server-soap
spec:
  ports:
    - port: 7878
      targetPort: 7878
  selector:
    app: tbc-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wow
  name: tbc-server
spec:
  selector:
    matchLabels:
      app: tbc-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tbc-server
    spec:
      initContainers:
        - name: check-mysql
          image: mysql
          command:
            - sh
            - -c
            - |            #!/bin/bash
              until mysql --connect-timeout=5 -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e ''; do
                >&2 echo "MySQL is unavailable - sleeping-30s"
                sleep 30
              done
          envFrom:
            - secretRef:
                name: tbc-secrets
      terminationGracePeriodSeconds: 120
      containers:
        - image: king607267/cmangos-tbc-server
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: 8085
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 8085
            periodSeconds: 30
          name: tbc-server
          lifecycle:
            preStop:
              exec:
                command: [ ".server restart", "60" ]
          resources:
            requests:
              cpu: "100m"
              memory: "650Mi"
            limits:
              cpu: "1"
              memory: "1.5Gi"
          stdin: true
          tty: true
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: tbc-secrets
                  key: TZ
            - name: LOGIN_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: tbc-secrets
                  key: LOGIN_DATABASE_INFO
            - name: WORLD_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: tbc-secrets
                  key: WORLD_DATABASE_INFO
            - name: CHARACTER_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: tbc-secrets
                  key: CHARACTER_DATABASE_INFO
            - name: LOGS_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: tbc-secrets
                  key: LOGS_DATABASE_INFO
          ports:
            - containerPort: 8085
              name: tbc-server
            - containerPort: 7878
              name: ser-cla-soap
          volumeMounts:
            - name: wow-nfs
              subPath: tbc/map
              mountPath: /etc/mangos/data
            - name: wow-nfs
              subPath: tbc/conf
              mountPath: /etc/mangos/conf
      volumes:
        - nfs:
            path: /mnt/nfs/WoW
            server: nfs.server
          name: wow-nfs