{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.cmangos.namespaceOverride }}
  name: {{ .Values.cmangos.type }}-mysql-svc
spec:
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: 3306
  selector:
    app: {{ .Values.cmangos.type }}-mysql
  type: {{ .Values.mysql.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wow
  name: {{ .Values.cmangos.type }}-mysql
spec:
  selector:
    matchLabels:
      app: {{ .Values.cmangos.type }}-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.cmangos.type }}-mysql
    spec:
      {{- if .Values.mysql.nodeSelector }}
      nodeSelector:
        {{ .Values.mysql.nodeSelector }}
      {{- end }}
      containers:
        - image: "king607267/cmangos-{{ .Values.cmangos.type }}-db:{{ .Values.mysql.tagName }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            exec:
              command:
                - cat
                - /var/lib/mysql/ready
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
          name: {{ .Values.cmangos.type }}-mysql
          env:
            - name: REALM_IP
              value: {{ .Values.mysql.realm.ip }}
            - name: I18N
              value: {{ .Values.mysql.i18n }}
            - name: CUSTOM_SQL_URL
              value: {{ .Values.mysql.custom_sql_URL }}
            - name: REALM_NAME
              value: {{ .Values.mysql.realm.name }}
            - name: REALM_PORT
              value: {{ .Values.mysql.realm.port | quote }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cmangos.type }}-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cmangos.type }}-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cmangos.type }}-secrets
                  key: MYSQL_USER
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: {{ .Values.cmangos.type }}-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: {{ .Values.cmangos.type }}-mysql
          hostPath:
            path: /data/mysql/{{ .Values.cmangos.type }}
            type: DirectoryOrCreate
      restartPolicy: {{ .Values.image.restartPolicy }}
{{- end -}}