{{- if .Values.mysql.enabled -}}
{{- if .Values.mysql.dbBackupJob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cmangos.type }}-backup-job
  namespace: {{ .Values.cmangos.namespaceOverride }}
spec:
  schedule: {{ .Values.job.dbBackup.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.job.dbBackup.ttlSecondsAfterFinished }}
      template:
        spec:
          containers:
            - name: {{ .Values.cmangos.type }}-backup
              image: mysql
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
                - | #!/bin/bash
                  path="/dbBackup/{{ .Values.cmangos.type }}/"$(date '+%Y-%m-%d')
                  mkdir -p $path && cd $path
                  mysqldump --no-tablespaces -t -u$MYSQL_USER -p$MYSQL_PASSWORD -P$MYSQL_PORT -h$MYSQL_HOST \
                  --databases {{ .Values.cmangos.type }}characters {{ .Values.cmangos.type }}realmd \
                  --ignore-table={{ .Values.cmangos.type }}realmd.antispam_blacklist \
                  --ignore-table={{ .Values.cmangos.type }}realmd.antispam_replacement \
                  --ignore-table={{ .Values.cmangos.type }}realmd.antispam_unicode_replacement \
                  --ignore-table={{ .Values.cmangos.type }}realmd.realmlist > "WoWDBback{{ .Values.cmangos.type }}_$(date '+%H%M').sql"
                  echo "dump success! "$(ls -hl)
              envFrom:
                - secretRef:
                    name: {{ .Values.cmangos.type }}-secrets
              volumeMounts:
                - name: wow-nfs
                  subPath: dbBackup
                  mountPath: /dbBackup
          volumes:
            - nfs:
                path: {{ .Values.nfs.path }}
                server: {{ .Values.nfs.server }}
              name: wow-nfs
          restartPolicy: Never
      backoffLimit: 0
{{ end }}
{{ end }}