kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ .Values.cmangos.type }}-gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: {{ .Values.cmangos.type }}-gateway
spec:
  gatewayClassName: {{ .Values.cmangos.type }}-gateway-class
  addresses:
    - address:
      type: IPAddress
      value: {{ .Values.gateway.ip }}
  listeners:
    - name: server
      protocol: TCP
      port: {{ .Values.gateway.server.port }}
      allowedRoutes:
        kinds:
          - kind: TCPRoute
    - name: realmd
      protocol: TCP
      port: {{ .Values.gateway.realmd.port }}
      allowedRoutes:
        kinds:
          - kind: TCPRoute
    - name: registration-http
      protocol: HTTP
      port: {{ .Values.gateway.registration.port }}
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
{{- if .Values.gateway.registration.tls.enabled }}
    - name: registration-https
      protocol: HTTPS
      hostname: {{ .Values.gateway.registration.domain }}
      port: {{ .Values.gateway.registration.tls.port }}
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          group: ""
          name: {{ .Values.cmangos.type }}-dns-issued-secret
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.cmangos.type }}-registration-route-http
spec:
  parentRefs:
    - name: {{ .Values.cmangos.type }}-gateway
      sectionName: registration-http
    - name: {{ .Values.cmangos.type }}-gateway
      sectionName: registration-https
  hostnames:
    - {{ .Values.gateway.registration.domain }}
  rules:
    - backendRefs:
        - name: {{ .Values.cmangos.type }}-registration-svc
          port: {{ .Values.registration.http.port }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ .Values.cmangos.type }}-server-route
spec:
  parentRefs:
    - name: {{ .Values.cmangos.type }}-gateway
      sectionName: server
  rules:
    - backendRefs:
        - name: {{ .Values.cmangos.type }}-server-svc
          port: {{ .Values.server.service.port }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ .Values.cmangos.type }}-realmd-route
spec:
  parentRefs:
    - name: {{ .Values.cmangos.type }}-gateway
      sectionName: realmd
  rules:
    - backendRefs:
        - name: {{ .Values.cmangos.type }}-realmd-svc
          port: {{ .Values.realmd.service.port }}