{{- if .Values.realmd.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.cmangos.namespaceOverride }}
  name: {{ .Values.cmangos.type }}-realmd-svc
spec:
  ports:
    - port: {{ .Values.realmd.service.port }}
      targetPort: 3724
  selector:
    app: {{ .Values.cmangos.type }}-realmd
  type: {{ .Values.realmd.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.cmangos.namespaceOverride }}
  name: {{ .Values.cmangos.type }}-realmd
spec:
  selector:
    matchLabels:
      app: {{ .Values.cmangos.type }}-realmd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.cmangos.type }}-realmd
    spec:
      {{- if .Values.realmd.nodeSelector }}
      nodeSelector:
        {{ .Values.realmd.nodeSelector }}
      {{- end }}
      initContainers:
        - name: check-mysql
          image: arey/mysql-client
          command:
            - sh
            - -c
            - |            #!/bin/bash
              until mysql -h $MYSQL_HOST -P${MYSQL_PORT:-3306} -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'USE {{ .Values.cmangos.type }}realmd; DESCRIBE db_ready;'; do
                >&2 echo "MySQL is unavailable - sleeping-30s"
                sleep 30
              done
          envFrom:
            - secretRef:
                name: {{ .Values.cmangos.type }}-secrets
      containers:
        - image: "king607267/cmangos-{{ .Values.cmangos.type }}-realmd:{{ .Values.realmd.tagName }}"
          name: {{ .Values.cmangos.type }}-realmd
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.realmd.service.port }}
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: {{ .Values.realmd.service.port }}
            periodSeconds: 30
          resources:
            {{- toYaml .Values.realmd.resources | nindent 12 }}
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cmangos.type }}-secrets
                  key: TZ
            - name: LOGIN_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cmangos.type }}-secrets
                  key: LOGIN_DATABASE_INFO
          ports:
            - containerPort: 3724
              name: {{ .Values.cmangos.type }}-realmd
      restartPolicy: {{ .Values.image.restartPolicy }}
{{ end }}