apiVersion: v1
kind: Secret
metadata:
  namespace: wow
  name: {{ .Values.cmangos.type }}-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "{{ .Values.mysql.root_password }}"
  MYSQL_USER: "{{ .Values.mysql.user }}"
  MYSQL_PASSWORD: "{{ .Values.mysql.password }}"
  MYSQL_HOST: "{{ .Values.cmangos.type }}-mysql-svc"
  LOGIN_DATABASE_INFO: "{{ .Values.cmangos.type }}-mysql-svc;{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}realmd"
  WORLD_DATABASE_INFO: "{{ .Values.cmangos.type }}-mysql-svc;{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}mangos"
  CHARACTER_DATABASE_INFO: "{{ .Values.cmangos.type }}-mysql-svc;{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}characters"
  LOGS_DATABASE_INFO: "{{ .Values.cmangos.type }}-mysql-svc;{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}logs"
  TZ: "{{ .Values.mysql.tz }}"