apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.cmangos.namespaceOverride }}
  name: {{ .Values.cmangos.type }}-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "{{ .Values.mysql.rootPassword }}"
  MYSQL_USER: "{{ .Values.mysql.user }}"
  MYSQL_PASSWORD: "{{ .Values.mysql.password }}"
  MYSQL_PORT: "{{ .Values.mysql.port }}"
  {{- if not .Values.mysql.enabled }}
  MYSQL_HOST: "{{ .Values.mysql.externalURL }}"
  LOGIN_DATABASE_INFO: "{{ .Values.mysql.externalURL }};{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}realmd"
  WORLD_DATABASE_INFO: "{{ .Values.mysql.externalURL }};{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}mangos"
  CHARACTER_DATABASE_INFO: "{{ .Values.mysql.externalURL }};{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}characters"
  LOGS_DATABASE_INFO: "{{ .Values.mysql.externalURL }};{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}logs"
  {{- else }}
  MYSQL_HOST: "{{ .Values.cmangos.type }}-mysql-svc"
  LOGIN_DATABASE_INFO: "{{ .Values.cmangos.type }}-mysql-svc;{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}realmd"
  WORLD_DATABASE_INFO: "{{ .Values.cmangos.type }}-mysql-svc;{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}mangos"
  CHARACTER_DATABASE_INFO: "{{ .Values.cmangos.type }}-mysql-svc;{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}characters"
  LOGS_DATABASE_INFO: "{{ .Values.cmangos.type }}-mysql-svc;{{ .Values.mysql.port }};{{ .Values.mysql.user }};{{ .Values.mysql.password }};{{ .Values.cmangos.type }}logs"
  {{- end }}
  TZ: "{{ .Values.mysql.tz }}"