{{ if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.cmangos.namespaceOverride }}
  name: {{ .Values.cmangos.type }}-server-svc
spec:
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 8085
  selector:
    app: {{ .Values.cmangos.type }}-server
  type: {{ .Values.server.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.cmangos.namespaceOverride }}
  name: {{ .Values.cmangos.type }}-soap-svc
spec:
  ports:
    - port: {{ .Values.server.service.soa.port }}
      targetPort: 7878
  selector:
    app: {{ .Values.cmangos.type }}-server
  type: {{ .Values.server.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.cmangos.namespaceOverride }}
  name: {{ .Values.cmangos.type }}-server
spec:
  selector:
    matchLabels:
      app: {{ .Values.cmangos.type }}-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.cmangos.type }}-server
    spec:
      {{- if .Values.server.nodeSelector }}
      nodeSelector:
        {{ .Values.server.nodeSelector }}
      {{- end }}
      initContainers:
        - name: check-mysql
          image: arey/mysql-client
          command:
            - sh
            - -c
            - | #!/bin/bash
              until mysql -h$MYSQL_HOST -P${MYSQL_PORT:-3306} -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'USE {{ .Values.cmangos.type }}realmd; DESCRIBE db_ready;'; do
                >&2 echo "MySQL is unavailable - sleeping-15s"
                sleep 15
              done
          envFrom:
            - secretRef:
                name: {{ .Values.cmangos.type }}-secrets
      terminationGracePeriodSeconds: 120
      containers:
        - image: "king607267/cmangos-{{ .Values.cmangos.type }}-server:{{ .Values.server.tagName }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.server.service.port }}
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: {{ .Values.server.service.port }}
            periodSeconds: 30
          name: {{ .Values.cmangos.type }}-server
          lifecycle:
            preStop:
              exec:
                command: [ ".server restart", "60" ]
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          stdin: true
          tty: true
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cmangos.type }}-secrets
                  key: TZ
            - name: LOGIN_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cmangos.type }}-secrets
                  key: LOGIN_DATABASE_INFO
            - name: WORLD_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cmangos.type }}-secrets
                  key: WORLD_DATABASE_INFO
            - name: CHARACTER_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cmangos.type }}-secrets
                  key: CHARACTER_DATABASE_INFO
            - name: LOGS_DATABASE_INFO
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cmangos.type }}-secrets
                  key: LOGS_DATABASE_INFO
          ports:
            - containerPort: 8085
              name: {{ .Values.cmangos.type }}-server
            - containerPort: 7878
              name: ser-cla-soap
          volumeMounts:
            - name: wow-nfs
              subPath: map/{{ .Values.cmangos.type }}
              mountPath: /etc/mangos/data
            - name: wow-nfs
              subPath: conf/{{ .Values.cmangos.type }}
              mountPath: /etc/mangos/conf
      restartPolicy: {{ .Values.image.restartPolicy }}
      volumes:
        - nfs:
            path: {{ .Values.nfs.path }}
            server: {{ .Values.nfs.server }}
          name: wow-nfs
{{ end }}